function sebas() {
    document.getElementById("con").innerHTML = ""
    +"<form class='form-register'>"
    +"<section>"
    +"<input class='controls1' type='text' name='nombres' id='nombres' placeholder='Nombre'><br>"
    +"<input class='controls2' type='text' name='apellidos' id='apellidos' placeholder='Apellido'><br>"
    +"<input class='controls3' type='email' name='correo' id='correo' placeholder='Correo'><br>"
    +"<select  class='opciones'>"
        +"<option>Tarjeta De Identidad</option>"
        +"<option>Numero de documento</option>"
    +"</select>"
    +"<input class='controls4' type='text'name='numero' de documento' id='numero de documento' placeholder='Numero de Documento'><br>"
    +"<input class='controls5' type='password' name='correo' id='correo' placeholder='Contraseña'><br>"
    +"<button><a class='boton href='#'>Agregar</a></button>"
    +"<button><a class='boton'href='menu.html'>Regresar</a></button>"
    
 
   +"</section>"
 +"</form>"
}

function lamao() {
    document.getElementById("con").innerHTML = ""
     +"<center>"
    +"<div class='container'>"
        +"<table>"
            +"<thead>"
                +"<tr>"
                    +"<th>N°</th>"
                    +"<th>Nombre</th>"
                    +"<th>Apellidos</th>"
                    +"<th>numero de documento</th>"
                    +"<th>correo</th>"
                    +"<th>numero de telefono</th>"
                +"</tr>"
            +"</thead>"
            +"<tbody>"
                +"<tr>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td></td>"
                    +"<td></td>"
                    +"<td></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>02</td>"
                    +"<td><input type='text'></td>"
                    +"<td></td>"
                    +"<td></td>"
                    +"<td></td>"
                    +"<td></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>03</td>"
                    +"<td></td>"
                    +"<td></td>"
                   +"<td></td>"
                    +"<td></td>"
                    +"<td></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>04</td>"
                    +"<td></td>"
                    +"<td></td>"
                    +"<td></td>"
                    +"<td></td>"
                    +"<td></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>05</td>"
                    +"<td></td>"
                    +"<td></td>"
                    +"<td></td>"
                    +"<td></td>"
                +"</tr>"
            +"</tbody>"
        +"</table>"
        +"<a href='menu.html'><input class='boton' type='submit' value='Regresar'></a>"
    +"</div>" 
    +"<center/>";
}